apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filterpods-chart.fullname" . }}
  labels:
    {{- include "filterpods-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "filterpods-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "filterpods-chart.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "filterpods-chart.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: POD_STATUS
          value: "{{ .Values.podStatus }}"
